// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// deltri_cpp
Rcpp::List deltri_cpp(std::vector<double> coords);
RcppExport SEXP _AlphaHullRangeModeller_deltri_cpp(SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(deltri_cpp(coords));
    return rcpp_result_gen;
END_RCPP
}
// delvor_rcpp
Rcpp::List delvor_rcpp(Rcpp::NumericMatrix x);
RcppExport SEXP _AlphaHullRangeModeller_delvor_rcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(delvor_rcpp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AlphaHullRangeModeller_deltri_cpp", (DL_FUNC) &_AlphaHullRangeModeller_deltri_cpp, 1},
    {"_AlphaHullRangeModeller_delvor_rcpp", (DL_FUNC) &_AlphaHullRangeModeller_delvor_rcpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_AlphaHullRangeModeller(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
