#' Fix alpha hulls generated from the package RcppAlphahul 
#'
#' Function written by chatGPT to fix improper `ahull` object generated by RcppAlphahull
#' 
#' @param x `ahull` object generated by the function ahull from the package RcppAlhahull
#' @param orig_points a matrix or data.frame of the original data points
#' @return `ahull` object
rcppah2ah <- function(x, orig_points, tol = 1e-10) {
  
  if (!inherits(x, "ahull")) stop("x must be an ahull object")
  if (is.data.frame(orig_points)) orig_points <- as.matrix(orig_points)
  if (!is.matrix(orig_points) || ncol(orig_points) != 2) {
    stop("orig_points must be a 2-column matrix of the original input coordinates")
  }
  
  arcs <- as.matrix(x$arcs)
  colnames(arcs) <- sub("^vx$", "v.x", sub("^vy$", "v.y", colnames(arcs)))
  
  if (!all(c("c1","c2","r","v.x","v.y","theta") %in% colnames(arcs))) {
    stop("x$arcs must contain c1,c2,r,v.x/vx,v.y/vy,theta")
  }
  
  arcs <- arcs[, c("c1","c2","r","v.x","v.y","theta"), drop = FALSE]
  
  ## ---- helpers ----
  
  unit_vec <- function(v, eps = 1e-15) {
    nv <- sqrt(sum(v * v))
    if (!is.finite(nv) || nv < eps) return(c(NA_real_, NA_real_))
    v / nv
  }
  
  angle_2pi <- function(v) {
    v <- unit_vec(v)
    if (anyNA(v)) return(NA_real_)
    a <- atan2(v[2], v[1])
    if (a < 0) a <- a + 2 * pi
    a
  }
  
  endpoint_coords <- function(a) {
    cc <- a[c("c1","c2")]
    r  <- a[["r"]]
    v  <- a[c("v.x","v.y")]
    th <- a[["theta"]]
    
    ang <- alphahull::anglesArc(v, th)
    p1 <- c(cc[1] + r * cos(ang[1]), cc[2] + r * sin(ang[1]))
    p2 <- c(cc[1] + r * cos(ang[2]), cc[2] + r * sin(ang[2]))
    list(p1 = p1, p2 = p2)
  }
  
  match_or_append <- function(pt, cutp, tol) {
    d <- abs(cutp[,1] - pt[1]) <= tol & abs(cutp[,2] - pt[2]) <= tol
    hit <- which(d)
    if (length(hit)) {
      list(idx = hit[1], cutp = cutp)
    } else {
      cutp <- rbind(cutp, pt)
      list(idx = nrow(cutp), cutp = cutp)
    }
  }
  
  ## ---- Step 1: initialize cutp like alphahull::ahull() ----
  cutp <- orig_points
  
  ## ---- Step 2: build initial indp from arc endpoints against cutp ----
  n.arc <- nrow(arcs)
  indp <- matrix(0, n.arc, 2)
  
  for (i in seq_len(n.arc)) {
    if (arcs[i, "r"] <= 0) next
    ep <- endpoint_coords(arcs[i, ])
    m1 <- match_or_append(ep$p1, cutp, tol)
    cutp <- m1$cutp
    m2 <- match_or_append(ep$p2, cutp, tol)
    cutp <- m2$cutp
    indp[i, ] <- c(m1$idx, m2$idx)
  }
  
  ## ---- Step 3: port the arc-splitting logic from alphahull::ahull() ----
  watch <- 1
  j <- 1
  
  while (watch <= n.arc) {
    while (j <= n.arc) {
      if (j != watch) {
        intersection <- alphahull::inter(
          arcs[watch, "c1"], arcs[watch, "c2"], arcs[watch, "r"],
          arcs[j,     "c1"], arcs[j,     "c2"], arcs[j,     "r"]
        )
        
        if (intersection$n.cut == 2) {
          v.arc <- unit_vec(c(arcs[watch, "v.x"], arcs[watch, "v.y"]))
          ang.OX <- angle_2pi(v.arc)
          if (is.na(ang.OX)) {
            j <- j + 1
            next
          }
          
          v.int <- unit_vec(intersection$v1)
          if (anyNA(v.int)) {
            j <- j + 1
            next
          }
          
          v.int.rot <- unit_vec(alphahull::rotation(v.int, ang.OX))
          if (anyNA(v.int.rot)) {
            j <- j + 1
            next
          }
          
          ang.v.int.rot.OX <- angle_2pi(v.int.rot)
          if (is.na(ang.v.int.rot.OX)) {
            j <- j + 1
            next
          }
          
          if (v.int.rot[2] >= 0) {
            angles <- c(
              -arcs[watch, "theta"],
              arcs[watch, "theta"],
              ang.v.int.rot.OX - intersection$theta1,
              ang.v.int.rot.OX + intersection$theta1
            )
            names(angles) <- c("theta1","theta2","beta1","beta2")
            ord <- names(sort(angles))
          } else {
            angles <- c(
              -arcs[watch, "theta"],
              arcs[watch, "theta"],
              -ang.v.int.rot.OX - intersection$theta1,
              -ang.v.int.rot.OX + intersection$theta1
            )
            names(angles) <- c("theta1","theta2","beta1","beta2")
            ord <- names(sort(angles))
          }
          
          if (sum(match(indp[watch, ], indp[j, ], nomatch = 0)) > 0) {
            # cases where arcs share an endpoint
            if (indp[watch, 1] == indp[j, 2]) {
              case <- 0
              if (all(ord == c("beta1","beta2","theta1","theta2"))) case <- 1
              else if (all(ord == c("theta1","beta1","beta2","theta2"))) case <- 2
              else if (all(ord == c("beta1","theta1","beta2","theta2"))) {
                ang.control <- (angles["theta1"] - angles["beta1"]) / 2
                case <- if (abs(ang.control) < 1e-5) 2 else 1
              }
              
              if (case == 2) {
                ang.middle2 <- (angles["theta2"] - angles["beta2"]) / 2
                v.new2 <- unit_vec(alphahull::rotation(c(1,0), -arcs[watch, "theta"] + ang.middle2 - ang.OX))
                if (anyNA(v.new2)) {
                  j <- j + 1
                  next
                }
                
                newp <- arcs[watch, 1:2] + arcs[watch, 3] * alphahull::rotation(v.new2, ang.middle2)
                cutp <- rbind(cutp, newp)
                inn <- nrow(cutp)
                
                arcs[watch, 4:6] <- c(v.new2, ang.middle2)
                indp[watch, 1] <- inn
                
                pmaux <- (cutp[inn, ] + cutp[indp[j, 1], ]) * 0.5
                dmaux <- pmaux - cutp[indp[j, 1], ]
                ndmaux <- sqrt(sum(dmaux^2))
                vaux <- pmaux - arcs[j, 1:2]
                nvaux <- sqrt(sum(vaux^2))
                if (nvaux <= 0 || !is.finite(nvaux)) {
                  j <- j + 1
                  next
                }
                th <- atan(ndmaux / nvaux)
                
                arcs[j, 4:6] <- c(vaux / nvaux, th)
                indp[j, 2] <- inn
              }
              
            } else if (indp[watch, 2] == indp[j, 1]) {
              case <- 0
              if (all(ord == c("theta1","theta2","beta1","beta2"))) case <- 1
              else if (all(ord == c("theta1","beta1","beta2","theta2"))) case <- 2
              else if (all(ord == c("theta1","beta1","theta2","beta2"))) {
                ang.control <- (angles["theta2"] - angles["beta2"]) / 2
                case <- if (abs(ang.control) < 1e-5) 2 else 1
              }
              
              if (case == 2) {
                ang.middle <- (angles["beta1"] - angles["theta1"]) / 2
                v.new <- unit_vec(alphahull::rotation(c(1,0), arcs[watch, "theta"] - ang.middle - ang.OX))
                if (anyNA(v.new)) {
                  j <- j + 1
                  next
                }
                
                newp <- arcs[watch, 1:2] + arcs[watch, 3] * alphahull::rotation(v.new, -ang.middle)
                cutp <- rbind(cutp, newp)
                inn <- nrow(cutp)
                
                arcs[watch, 4:6] <- c(v.new, ang.middle)
                indp[watch, 2] <- inn
                
                pmaux <- (cutp[inn, ] + cutp[indp[j, 2], ]) * 0.5
                dmaux <- pmaux - cutp[indp[j, 2], ]
                ndmaux <- sqrt(sum(dmaux^2))
                vaux <- pmaux - arcs[j, 1:2]
                nvaux <- sqrt(sum(vaux^2))
                if (nvaux <= 0 || !is.finite(nvaux)) {
                  j <- j + 1
                  next
                }
                th <- atan(ndmaux / nvaux)
                
                arcs[j, 4:6] <- c(vaux / nvaux, th)
                indp[j, 1] <- inn
              }
            }
            
          } else if (all(ord == c("theta1","beta1","beta2","theta2"))) {
            # split the watched arc into two pieces, like alphahull::ahull()
            v.arcj <- unit_vec(c(arcs[j, "v.x"], arcs[j, "v.y"]))
            ang.OXj <- angle_2pi(v.arcj)
            if (is.na(ang.OXj)) {
              j <- j + 1
              next
            }
            
            v.intj <- unit_vec(intersection$v2)
            if (anyNA(v.intj)) {
              j <- j + 1
              next
            }
            
            v.int.rotj <- unit_vec(alphahull::rotation(v.intj, ang.OXj))
            if (anyNA(v.int.rotj)) {
              j <- j + 1
              next
            }
            
            ang.v.int.rot.OXj <- angle_2pi(v.int.rotj)
            if (is.na(ang.v.int.rot.OXj)) {
              j <- j + 1
              next
            }
            
            if (v.int.rotj[2] >= 0) {
              anglesj <- c(
                -arcs[j, "theta"],
                arcs[j, "theta"],
                ang.v.int.rot.OXj - intersection$theta2,
                ang.v.int.rot.OXj + intersection$theta2
              )
              names(anglesj) <- c("theta1","theta2","beta1","beta2")
              ordj <- names(sort(anglesj))
            } else {
              anglesj <- c(
                -arcs[j, "theta"],
                arcs[j, "theta"],
                -ang.v.int.rot.OXj - intersection$theta2,
                -ang.v.int.rot.OXj + intersection$theta2
              )
              names(anglesj) <- c("theta1","theta2","beta1","beta2")
              ordj <- names(sort(anglesj))
            }
            
            if (all(ordj == c("theta1","beta1","beta2","theta2"))) {
              ang.middle  <- (angles["beta1"]  - angles["theta1"]) / 2
              ang.middle2 <- (angles["theta2"] - angles["beta2"]) / 2
              
              v.new  <- unit_vec(alphahull::rotation(c(1,0),  arcs[watch, "theta"] - ang.middle  - ang.OX))
              v.new2 <- unit_vec(alphahull::rotation(c(1,0), -arcs[watch, "theta"] + ang.middle2 - ang.OX))
              if (anyNA(v.new) || anyNA(v.new2)) {
                j <- j + 1
                next
              }
              
              arcs <- rbind(arcs, c(arcs[watch, 1:3], v.new2[1], v.new2[2], ang.middle2))
              arcs[watch, ] <- c(arcs[watch, 1:3], v.new[1], v.new[2], ang.middle)
              n.arc <- nrow(arcs)
              
              np1 <- arcs[watch, 1:2] + arcs[watch, 3] * alphahull::rotation(v.new,  -ang.middle)
              np2 <- arcs[watch, 1:2] + arcs[watch, 3] * alphahull::rotation(v.new2,  ang.middle2)
              
              indold <- indp[watch, 2]
              inn1 <- nrow(cutp) + 1
              inn2 <- nrow(cutp) + 2
              
              indp[watch, 2] <- inn1
              indp <- rbind(indp, c(inn2, indold))
              
              cutp <- rbind(cutp, np1, np2)
              
              indoldj <- indp[j, 1]
              indp[j, 1] <- inn1
              indp <- rbind(indp, c(indoldj, inn2))
              
              pmaux <- (cutp[inn1, ] + cutp[indp[j, 2], ]) * 0.5
              dmaux <- pmaux - cutp[indp[j, 2], ]
              ndmaux <- sqrt(sum(dmaux^2))
              vaux <- pmaux - arcs[j, 1:2]
              nvaux <- sqrt(sum(vaux^2))
              if (nvaux <= 0 || !is.finite(nvaux)) {
                j <- j + 1
                next
              }
              th <- atan(ndmaux / nvaux)
              arcs[j, 4:6] <- c(vaux / nvaux, th)
              
              pmaux <- (cutp[inn2, ] + cutp[indoldj, ]) * 0.5
              dmaux <- pmaux - cutp[indoldj, ]
              ndmaux <- sqrt(sum(dmaux^2))
              vaux <- pmaux - arcs[j, 1:2]
              nvaux <- sqrt(sum(vaux^2))
              if (nvaux <= 0 || !is.finite(nvaux)) {
                j <- j + 1
                next
              }
              th <- atan(ndmaux / nvaux)
              arcs <- rbind(arcs, c(arcs[j, 1:3], vaux / nvaux, th))
              n.arc <- nrow(arcs)
            }
          }
        }
      }
      j <- j + 1
    }
    watch <- watch + 1
    j <- 1
  }
  
  ## ---- Step 4: same final ordering as alphahull::ahull() ----
  ord.old <- seq_len(nrow(indp))
  ord.new <- numeric()
  
  while (length(ord.new) < length(ord.old)) {
    if (length(ord.new) == 0) {
      ord.new <- 1
    } else {
      ord.new <- c(ord.new, ord.old[-ord.new][1])
    }
    coinc <- match(indp[ord.new[length(ord.new)], 2], indp[-ord.new, 1])
    while (!is.na(coinc)) {
      ord.new <- c(ord.new, ord.old[-ord.new][coinc])
      coinc <- match(indp[ord.new[length(ord.new)], 2], indp[-ord.new, 1])
    }
  }
  
  indp <- indp[ord.new, , drop = FALSE]
  ahull.arcs <- cbind(arcs[ord.new, , drop = FALSE], indp)
  colnames(ahull.arcs) <- c("c1","c2","r","v.x","v.y","theta","end1","end2")
  
  x$arcs <- ahull.arcs
  x$xahull <- cutp
  x
}