# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

deltri_cpp <- function(coords) {
    .Call(`_AlphaHullRangeModeller_deltri_cpp`, coords)
}

delvor_rcpp <- function(x) {
    .Call(`_AlphaHullRangeModeller_delvor_rcpp`, x)
}

